{% set name = "pyxlsx" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxlsx-{{ version }}.tar.gz
  sha256: 2e8dfdabb92651896c64ccfd1900dc0edfa1f93ed830834a7d70ccf685f1d3db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - openpyxl >=3.0.3
    - pycel

test:
  imports:
    - pyxlsx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fortfall/pyxlsx
  license: MIT
  license_file: LICENSE
  summary: A package to read/write xlsx worksheet like dictionary, based on openpyxl.

extra:
  recipe-maintainers:
    - hechth
